# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC PROD PR Status Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
    paths:
      - 'Definitions/**'

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan to PR comment
    uses: ./.github/workflows/plan-pr-comment.yml
    with:
      pacEnvironmentSelector: tenant
      planGitHubEnvironment: tenant-plan
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit