# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC PROD Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'Definitions/**'

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan prod
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: tenant
      planGitHubEnvironment: tenant-plan
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  planPRComment:
    name: Plan prod
    uses: ./.github/workflows/plan-pr-comment.yml
    with:
      pacEnvironmentSelector: tenant
      planGitHubEnvironment: tenant-plan
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployPolicy:
    name: Deploy prod Policy Changes
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes' && startsWith(github.ref, 'refs/heads/main')
    uses: ./.github/workflows/deploy-policy.yml
    with:
      pacEnvironmentSelector: tenant
      planGitHubEnvironment: tenant-deploy-policy
      PAC_INPUT_FOLDER: "$(GITHUB_WORKSPACE)/plans-tenant"
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployRoles:
    name: Deploy prod Role Changes
    needs: plan
    if: needs.plan.outputs.deployRoleChanges == 'yes' && startsWith(github.ref, 'refs/heads/main')
    uses: ./.github/workflows/deploy-roles.yml
    with:
      pacEnvironmentSelector: tenant
      planGitHubEnvironment: tenant-deploy-roles
      PAC_INPUT_FOLDER: "$(GITHUB_WORKSPACE)/plans-tenant"
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit